import React, { useState } from 'react';
import { PenTool, Copy, Check, Heart, Mail, Share2 } from 'lucide-react';
import { copyToClipboard } from '../utils/helpers';

export default function TravelJournalPostcard({ travelJournal, instagramCaption, destination }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    if (!instagramCaption) return;
    try {
      await copyToClipboard(instagramCaption);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy caption:', err);
    }
  };

  const cleanDestination = destination || 'My Destination';

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
      
      {/* 1. Travel Postcard & Journal (8 cols) */}
      <div className="lg:col-span-8 bg-white dark:bg-zinc-900 border border-slate-100 dark:border-zinc-800 rounded-3xl p-6 shadow-sm space-y-6">
        
        <div className="flex items-center gap-2 border-b border-slate-100 dark:border-zinc-800/80 pb-4">
          <div className="w-8 h-8 rounded-xl bg-pink-500/10 flex items-center justify-center text-pink-500">
            <PenTool className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-lg font-bold text-slate-800 dark:text-zinc-100 font-display">
              Travel Postcard & Journal
            </h3>
            <p className="text-[11px] font-semibold text-slate-500 dark:text-zinc-400">
              Immersive, creative memories generated by Culture Compass.
            </p>
          </div>
        </div>

        {/* Physical Postcard Mockup UI */}
        <div className="relative bg-[#fcf9f2] dark:bg-zinc-950 border border-slate-200 dark:border-zinc-800 rounded-2xl p-6 md:p-8 shadow-md text-slate-800 dark:text-zinc-200 overflow-hidden flex flex-col md:flex-row gap-8 items-stretch font-serif">
          
          {/* Postcard Background stamp watermark */}
          <div className="absolute top-4 right-4 w-12 h-14 border-2 border-dashed border-rose-500/40 rounded flex items-center justify-center text-rose-500/40 select-none transform rotate-6 font-sans font-black text-xs">
            COMPASS
          </div>

          {/* Left Side: Handwritten Message */}
          <div className="flex-1 space-y-4 pr-0 md:pr-6 border-r-0 md:border-r border-slate-350/30 dark:border-zinc-800/50 flex flex-col justify-between">
            <div className="space-y-3">
              <h4 className="text-sm font-bold text-rose-550 uppercase tracking-widest font-sans not-italic">
                Dear Diary,
              </h4>
              <p className="text-sm leading-relaxed italic text-slate-700 dark:text-zinc-300 antialiased font-serif whitespace-pre-line">
                {travelJournal}
              </p>
            </div>
            
            <div className="text-xs font-bold text-slate-400 dark:text-zinc-650 font-sans not-italic pt-4 flex items-center gap-1">
              <Heart className="w-3.5 h-3.5 fill-rose-550 text-rose-550 animate-pulse" />
              <span>Created dynamically via Culture Compass AI</span>
            </div>
          </div>

          {/* Right Side: Stamp & Address lines */}
          <div className="w-full md:w-[180px] flex flex-col justify-between items-stretch py-2 shrink-0 space-y-8 font-sans">
            
            {/* Postage Stamp */}
            <div className="self-end w-14 h-16 bg-gradient-to-tr from-amber-500 to-rose-500 rounded border-2 border-double border-white shadow-md flex flex-col items-center justify-center text-white p-1 select-none transform hover:rotate-2 transition-transform">
              <span className="text-[8px] font-black tracking-widest">POSTAGE</span>
              <span className="text-lg">🧭</span>
              <span className="text-[7px] font-bold mt-1">CULTURE AI</span>
            </div>

            {/* Address lines */}
            <div className="space-y-4 text-xs font-bold text-slate-400 dark:text-zinc-550">
              <div className="border-b border-slate-300 dark:border-zinc-800 pb-1 italic font-serif text-slate-700 dark:text-zinc-300">
                To: Fellow Explorer
              </div>
              <div className="border-b border-slate-300 dark:border-zinc-800 pb-1 italic font-serif text-slate-700 dark:text-zinc-300">
                At: {cleanDestination}
              </div>
              <div className="border-b border-slate-300 dark:border-zinc-800 pb-1 uppercase tracking-widest text-[8px] font-black text-rose-500/80">
                ★ GLOBAL HERITAGE ★
              </div>
            </div>

          </div>

        </div>

      </div>

      {/* 2. Instagram Social Caption (4 cols) */}
      <div className="lg:col-span-4 bg-white dark:bg-zinc-900 border border-slate-100 dark:border-zinc-800 rounded-3xl p-6 shadow-sm space-y-4">
        
        <div className="flex items-center gap-2 border-b border-slate-100 dark:border-zinc-800/80 pb-4">
          <div className="w-8 h-8 rounded-xl bg-indigo-500/10 flex items-center justify-center text-indigo-500">
            <Share2 className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-lg font-bold text-slate-800 dark:text-zinc-100 font-display">
              Social Caption
            </h3>
            <p className="text-[11px] font-semibold text-slate-500 dark:text-zinc-400">
              Shareable Instagram stories.
            </p>
          </div>
        </div>

        {/* Caption Display card */}
        <div className="bg-slate-50 dark:bg-zinc-950 border border-slate-100 dark:border-zinc-900 p-4 rounded-2xl flex flex-col justify-between h-[230px]">
          <p className="text-xs font-semibold leading-relaxed text-slate-650 dark:text-zinc-300 overflow-y-auto pr-1 select-all font-sans whitespace-pre-line italic">
            "{instagramCaption}"
          </p>

          <button
            onClick={handleCopy}
            className="mt-4 w-full inline-flex items-center justify-center gap-1.5 px-4 py-2.5 bg-indigo-550 hover:bg-indigo-650 text-white rounded-xl text-xs font-bold shadow-xs transition-all cursor-pointer focus:outline-none focus:ring-2 focus:ring-indigo-500"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 stroke-[3]" />
                Copied Caption!
              </>
            ) : (
              <>
                <Copy className="w-4 h-4" />
                Copy Caption
              </>
            )}
          </button>
        </div>

      </div>

    </div>
  );
}
